import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import { SessionProvider } from '@/auth';
import { QueryClientProvider } from '@/lib/queryClient-provider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, 'overflow-hidden flex flex-col')}>
        <QueryClientProvider>
          <SessionProvider>
            <Navbar />
            <div className="overflow-auto flex-grow flex flex-col">
              {children}
            </div>
            <Toaster />
          </SessionProvider>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
      </body>
    </html>
  );
}
